### ISSUE TITLE
Issue #04 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [charles-tyra/sahara#4]
# Sample State
- [X] State shape is flat!
- [X] State's keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [ ] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
1. First thing I'm noticing is that your Users have first and last names, but that isn't in your frontend state. That's worth adding.
2. In addition to this, we would want our `user` and `cart` slices of state to be nested under `users` and `carts` instead of the singular.
3. I know you're still working on your carts and items. I've left some notes on your Schema that might clarify how they should relate to one another and help you form their state shape.

**Comment by charles-tyra** [comment]
1. That's in line with the question that I had during the mini-lecture yesterday, took a bit of a step back and want to see the piece as a whole picture and really think about what I want for each of the pieces before jumping into the project - don't want so much making changes on the fly because that would add confusion unnecessary work when completing the project front to back.

Appreciate the rest of the feedback, will take a closer look at it tomorrow when I have a clear mind. Will attempt to have at least a soft template for each of the routes / sample states by the end of the night as a guideline and a jumping off point.

**Comment by keginzburg** [comment]
This looks really solid!
